name: "Export et Déploiement Web"
on:
  push:
    branches:
      - master  # Ajustez si votre branche principale s'appelle 'master'

permissions:
  contents: write

jobs:
  export-web:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.6.2 # Godot 4 (ex: 4.2.2)
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup des templates d'export Godot
        run: |
          mkdir -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/* ~/.local/share/godot/export_templates/ || true

      - name: Création des dossiers de build
        run: mkdir -v -p build/web

      - name: Export Automatique en HTML5
        run: godot --headless --export-release "Web" build/web/index.html

      - name: Déploiement sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web # Le dossier où le jeu a été exporté
          branch: gh-pages # La branche dédiée au site web de votre jeu
